-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 00:42:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salesflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salesflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salesflow` DEFAULT CHARACTER SET utf8 ;
USE `salesflow` ;

-- -----------------------------------------------------
-- Table `salesflow`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `img_url` VARCHAR(250) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco_compra` DECIMAL(10,2) NOT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `quantidade` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `comissao` DECIMAL(3,2) NOT NULL,
  `img_url` VARCHAR(250) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `fornecedor_idfornecedor` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_idfornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `salesflow`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`venda_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`venda_tipo` (
  `idvenda_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvenda_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `descricao` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `venda_tipo_idvenda_tipo` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  INDEX `fk_venda_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_venda_venda_tipo1_idx` (`venda_tipo_idvenda_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `salesflow`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `salesflow`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `salesflow`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_venda_tipo1`
    FOREIGN KEY (`venda_tipo_idvenda_tipo`)
    REFERENCES `salesflow`.`venda_tipo` (`idvenda_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`campanha` (
  `idcampanha` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `qtde_vendas` INT NOT NULL,
  `img_url` VARCHAR(250) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `venda_tipo_idvenda_tipo` INT NOT NULL,
  PRIMARY KEY (`idcampanha`),
  INDEX `fk_campanha_venda_tipo1_idx` (`venda_tipo_idvenda_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_campanha_venda_tipo1`
    FOREIGN KEY (`venda_tipo_idvenda_tipo`)
    REFERENCES `salesflow`.`venda_tipo` (`idvenda_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
