-- MySQL Script generated by MySQL Workbench
-- Tue Nov 18 16:33:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salesflow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salesflow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salesflow` DEFAULT CHARACTER SET utf8 ;
USE `salesflow` ;

-- -----------------------------------------------------
-- Table `salesflow`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `min_vendas` INT NOT NULL,
  `max_vendas` INT NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `idade` INT NOT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `status_idstatus` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_funcionario_status1_idx` (`status_idstatus` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `salesflow`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `preco_compra` DECIMAL(10,2) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `comissao` DECIMAL(3,2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `validade` DATETIME NULL,
  `fornecedor_idfornecedor` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_idfornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `salesflow`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`categoria_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`categoria_venda` (
  `idcategoria_venda` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcategoria_venda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `n_parcelas` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `categoria_venda_idcategoria_venda` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_vendas_funcionario_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  INDEX `fk_vendas_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_venda_categoria_venda1_idx` (`categoria_venda_idcategoria_venda` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_funcionario`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `salesflow`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `salesflow`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_categoria_venda1`
    FOREIGN KEY (`categoria_venda_idcategoria_venda`)
    REFERENCES `salesflow`.`categoria_venda` (`idcategoria_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesflow`.`campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesflow`.`campanha` (
  `idcampanha` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `vendas` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_final` DATETIME NULL,
  `venda_categoria` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`idcampanha`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
